version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    image: django/leon
    container_name: django-leon
    hostname: dev-leon
    volumes:
       - ./app:/app
    # command: sleep 3600