version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    image: django/benchmark
    container_name: django-benchmark
    hostname: dev-benchmark
    volumes:
       - ./app:/app
    # command: sleep 3600