version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    image: django/benchmark
    container_name: django-benchmark
    hostname: dev-benchmark
    ports:
    - 8080:8080
    - 8888:8888
    volumes:
       - ./app:/app
