version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    image: django/scaffold
    container_name: django-scaffold
    hostname: django-dev-scaffold
    volumes:
       - ./app:/app
    # command: sleep 3600